{
 "title": "Test-Service-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API: Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"/user/{userId}\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=\"/user/{userId}\"}[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{uri=\"/user/{userId}\"}[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "NGINX: Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "API: RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX: RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API: Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX: Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  }
 ]
}